name: gnu_web_dashboard
description: "gnu_web_dashboard"
publish_to: 'none'

version: 1.0.0+1
build-name: GNU_Web_Dashboard

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ### State Managing
  get_it: ^8.0.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.7.1

  ### Network
  mqtt_client: ^10.5.1
  uuid: ^4.5.1
  dio: ^5.8.0+1
  gsheets: ^0.5.0

  ### Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animated_toggle_switch: ^0.8.3
  dropdown_search: ^6.0.2
  omni_datetime_picker: ^2.1.1
  trina_grid:
    git:
      url: https://github.com/doonfrs/trina_grid.git
      ref: main
  fl_chart: ^0.70.2
  fluttertoast: ^8.2.12
  loading_indicator: ^3.1.1
  responsive_framework: ^1.5.1
  dotted_line: ^3.2.3

  ### Debug
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/test/
    - assets/env/
  fonts:
    - family: Pretendard Variable
      fonts:
        - asset: assets/font/PretendardVariable.ttf
          weight: 400
